# SOPS configuration — specifies which age public keys can decrypt.
# Matches .env.local, .env.prod, and .env.dev files (both plain and .enc encrypted).
# Generate a keypair: age-keygen -o key.txt

creation_rules:
  - path_regex: \.env\.(local|prod|dev)(\.enc)?$
    age: >-
      age1wravpjmed26772xfjhawmnsnc4933htapg6y5xseqml0jdv8z9hqemzhcr,
      age1ysddqggsx3h8zkv7xn3z26sjak5pqms6pyqhnky9ukrvpk7es5jsayz8w7,
      age1pgxk292zq30wafwg03gge7hu5dlu3h7yfldp2y8kqekfaljjky7s752uwy,
      age1qn0x93jhqjpqwvx5tgxnrwq5e3vuzur9whrkdnrvapd58esm45rqfkuxqh,
      age1h86dek80u5t677tsparz395uk3zvz4yuj9m5t2v2nsdfsvyjmafsra5yt7,
      age1vfhyk6wmt993dezz5wjf6n3ynkd6xptv2dr0qdl6kmttev9lh5dsfjfs3h
